name: UnitTests
on:
  push

jobs:
  testing:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Run Unit Tests
        run: bash ./gradlew test
